### ISSUE TITLE
Can't succeed to use the script

### ISSUE THREAD

**Issue by Synochy** [slightlynybbled/tol-stack#2]
Hello,

I am very interested by your tool !
But unfortunately I didn't succeed to run it.
I used PyCharm and when I run the script (_main_.py)I have the following error: _WARNING:__main__:no files found_

I can't find where to put the example file (.yml) to make it run properly.

Thanks by advance for your help,
Best regards,

**Comment by slightlynybbled** [comment]
You have to specify the file to run.

For instance, from the command line:

    $> tol_stack -f examples/max_length.yml

Using pycharm, you can provide the parameters by clicking the down arrow by your executing configuration and selecting `Edit Configurations`.  Once in there, use the `Parameters` and specify `-f examples/max_length.yml`.

The `concentricity.yml` example is in progress and currently broken... i'll take a look since there is some interest.

Thanks,

j
